### ISSUE TITLE
GalaxyDemo无法使用

### ISSUE THREAD

**Issue by carpenter-l** [outlaws-bai/GalaxyDemo#2]
在启动GalaxyDemo靶场之后无法发起请求
![image](https://github.com/user-attachments/assets/f1202279-8cb0-4d0e-b8d0-f8273d8ca7cb)

**Comment by outlaws-bai** [comment]
无法复现，请提供下抓到的包

**Comment by outlaws-bai** [comment]
长时间未回复，close

**Comment by 1491342590** [comment]
<img width="1052" height="671" alt="Image" src="https://github.com/user-attachments/assets/8d1f6b09-de1e-4c00-b933-64c737efc968" />

<img width="1133" height="453" alt="Image" src="https://github.com/user-attachments/assets/00083b87-4373-4813-b9e4-d69f8815e58e" />
我也是，我再去试试改一下代码

**Comment by 1491342590** [comment]
<img width="1078" height="461" alt="Image" src="https://github.com/user-attachments/assets/82ba31dc-cebe-427d-bbff-336705cc0b42" />问题出在这里，这个文件得科学上网才能访问，科学上网后就能发包了！
科学上网
科学上网
科学上网

**Comment by 1491342590** [comment]
我还发现只要正常科学上网一次，后面就可以直接使用了
因为科学上网后 CDN 资源被浏览器缓存了~

**Comment by outlaws-bai** [comment]
已优化https://github.com/outlaws-bai/GalaxyDemo/commit/08082a0788368d489b9bdc328b5de975ceba736d
